spring:
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mysql://docker.for.mac.host.internal:3306/openstack?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: openstack
      password: Ui#(23@
      maximum-pool-size: 5
      connection-test-query: select 1
      max-lifetime: 300000

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/mysql/*Mapper.xml
  config-location: classpath:jpaConfig-mysql.xml

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://docker.for.mac.host.internal:30140/eureka/
    enabled: true
    register-with-eureka: true