
spring:
  application:
    name: api-gateway-manage
  security:
    enabled: false

  main:
    allow-bean-definition-overriding: true

  messages:
    basename: i18n/message
    encoding: UTF-8

  mvc:
    static-path-pattern: /static/
    interceptors:
      resource-handler-registry:
        enabled: true
        entries:
          - handlers: /hbq969-dict/**
            locations: classpath:/static/hbq969-dict/
          - handlers: /ui-gw/**
            locations: classpath:/static/ui-gw/
      api-safe:
        enabled: true
        include-path-patterns: /ui-gw/**,/hbq969-dict/**
        header-name: api-safe-token
        header-value-regex: 8DC75E91D4E143CF94BA29C46C43B24B
      mdc:
        enabled: true

  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:h2:~/.h2/gateway
      driver-class-name: org.h2.Driver
      username: openstack
      password: ENC(CfdRDiDsKIHgJ+NDJlILeW966Jc/KzFsloWc42DildlR7/6utLnxdjI8ibk/46Q0)
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  cloud:
    gateway:
      enabled: false


server:
  port: 30139

mybatis:
  mapper-locations: classpath*:mappers/*.xml,classpath*:**/mapper/common/*Mapper.xml,classpath*:**/mapper/embedded/*Mapper.xml
  type-aliases-package: com.github.hbq969.gateway
  config-location: classpath:jpaConfig.xml

# gateway endpoint端点
gateway:
  endpoint:
    refresh:
      host: http://docker.for.mac.host.internal:30131
      uri: /gateway-dashboard/route-ext/load
      url: ${gateway.endpoint.refresh.host}${gateway.endpoint.refresh.uri}

# 使用那种方式通知路由变化, 支持http、kafka
route:
  notified:
    way: http
    master-service-id: API-GATEWAY-MASTER

# 内嵌数据库监听端口
embedded:
  enabled: true
  datasource:
    port: 30135

# 字典
dict:
  enabled: true
  reload:
    cron: 0 */10 * * * *

swagger:
  enabled: true
  base-package: com
  api-info:
    title: api-gateway dashboard api接口
    description: 网关维护管理接口

encrypt:
  config:
    enabled: true

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:30140/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    enabled: false